In [ ]:
import numpy as np
n1=np.array([10,20,40,50]) # single dimensional array
n1

array([10, 20, 40, 50])

In [ ]:
n1.ndim

1

In [ ]:
n2= np.array([[1,2,3,4],[4,3,2,1]]) #multi dimensional 
n2



array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
n2.ndim


2

In [ ]:
m1=np.zeros((4,5))
m1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n1=np.ones((3,8)),
n1

(array([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]),)

In [ ]:
n2= np.full((3,4),65)
n2

array([[65, 65, 65, 65],
       [65, 65, 65, 65],
       [65, 65, 65, 65]])

In [ ]:
n2= np.arange(10,20,3)
n2

array([10, 13, 16, 19])

In [ ]:
b2 = np.arange(20,68)
b2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67])

In [ ]:
n1=np.random.randint(1,100,5)
n1

array([99, 81,  4, 23, 10])

In [ ]:
n1= np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
n1.shape

(2, 4)

In [ ]:
n1.shape=(4,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
n1=np.array([10,23,45,56])
n2= np.array([23,45,67,89])
np.vstack([n1,n2])

array([[10, 23, 45, 56],
       [23, 45, 67, 89]])

In [ ]:
n1=np.array([10,23,45,56])
n2= np.array([23,45,67,89])
np.hstack([n1,n2])

array([10, 23, 45, 56, 23, 45, 67, 89])

In [ ]:
n1=np.array([10,23,45,56])
n2= np.array([23,45,67,89])
np.stack([n1,n2])

array([[10, 23, 45, 56],
       [23, 45, 67, 89]])

In [ ]:
z=np.array([1,45,678,98])
z1=np.array([46,677,89,0])
z2=np.array([45,67,889,41])
z3=np.array([12,13,14,15])
np.stack([z,z1,z2,z3])

array([[  1,  45, 678,  98],
       [ 46, 677,  89,   0],
       [ 45,  67, 889,  41],
       [ 12,  13,  14,  15]])

In [ ]:
z=np.array([1,45,678,98])
z1=np.array([46,677,89,0])
z2=np.array([45,67,889,41])
z3=np.array([12,13,14,15])
np.vstack([z,z1,z2,z3])

array([[  1,  45, 678,  98],
       [ 46, 677,  89,   0],
       [ 45,  67, 889,  41],
       [ 12,  13,  14,  15]])

In [ ]:
z=np.array([1,45,678,98])
z1=np.array([46,677,89,0])
z2=np.array([45,67,889,41])
z3=np.array([12,13,14,15])
np.column_stack([z,z1,z2,z3])

array([[  1,  46,  45,  12],
       [ 45, 677,  67,  13],
       [678,  89, 889,  14],
       [ 98,   0,  41,  15]])

In [ ]:
z=np.array([1,45,678,98])
z1=np.array([46,677,89,0])
z2=np.array([45,67,889,41])
z3=np.array([12,13,14,15])
np.hstack([z,z1,z2,z3])

array([  1,  45, 678,  98,  46, 677,  89,   0,  45,  67, 889,  41,  12,
        13,  14,  15])

In [ ]:
s1=np.array([10,20,30,40,50])
s1


array([10, 20, 30, 40, 50])

In [ ]:
s2=np.array([70,80,30,65,40])
s2

array([70, 80, 30, 65, 40])

In [ ]:
np.intersect1d(s1,s2)

array([30, 40])

In [ ]:
np.setdiff1d(s2,s1)

array([65, 70, 80])

In [ ]:
np.setdiff1d(s1,s2)

array([10, 20, 50])

In [ ]:
d=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
d1=np.array([[1,2,23,34,56],[8,76,89,90,78]])
d1

array([[ 1,  2, 23, 34, 56],
       [ 8, 76, 89, 90, 78]])

In [ ]:
np.intersect1d(d,d1)

array([1, 2, 8])

In [ ]:
np.setdiff1d(d,d1)

array([ 3,  4,  5,  6,  7,  9, 10])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40])
n2=np.array([15,25,35,45])

In [ ]:
np.sum([n1,n2])

220

In [ ]:
np.sum([n1,n2],axis=0)

array([25, 45, 65, 85])

In [ ]:
np.sum([n1,n2],axis=1)

array([100, 120])

In [ ]:
n1+1


array([11, 21, 31, 41])

In [ ]:
n1-5

array([ 5, 15, 25, 35])

In [ ]:
n1*2

array([20, 40, 60, 80])

In [ ]:
n1/2

array([ 5., 10., 15., 20.])

In [ ]:
n1//2

array([ 5, 10, 15, 20])

In [ ]:
n1**2

array([ 100,  400,  900, 1600])

In [ ]:
n1^3

array([ 9, 23, 29, 43])

In [ ]:
n1%3

array([1, 2, 0, 1])

In [ ]:
n1%2

array([0, 0, 0, 0])

In [ ]:
n1=np.random.randint(1,45,6)
n1


array([ 2,  4,  6, 42,  5, 12])

In [ ]:
np.mean(n1)

11.833333333333334

In [ ]:
np.median(n1)

5.5

In [ ]:
np.std(n1)

13.837348814791877

In [ ]:
n1

array([ 2,  4,  6, 42,  5, 12])

In [ ]:
np.save("my_array",n1)

In [ ]:
new_n1=np.load("my_array.npy")
new_n1

array([ 2,  4,  6, 42,  5, 12])

## **pandas**

# New Section

In [ ]:
import pandas as pd
s1=pd.Series([1,2,3,4,5,6])
s1


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
s1=pd.Series([1,2,3,4,5,6],index=['i','ii','iii','iv','v','vi'])
s1

i      1
ii     2
iii    3
iv     4
v      5
vi     6
dtype: int64

In [ ]:
#series object from dictonary
s2=pd.Series({'a':12,'b':13,'c':14,'d':15})
s2


a    12
b    13
c    14
d    15
dtype: int64

In [ ]:
s2=pd.Series({'a':12,'b':13,'c':14,'d':15},index=['d','c','b','a'])
s2


d    15
c    14
b    13
a    12
dtype: int64

In [ ]:
s2=pd.Series({'a':12,'b':13,'c':14,'d':15},index=['d','c','b','a','e'])
s2

d    15.0
c    14.0
b    13.0
a    12.0
e     NaN
dtype: float64

In [ ]:
l1=pd.Series([1,2,3,4,5,6,7,8,9])
l1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
l1[4]

5

In [ ]:
l1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
l1[-3:]

6    7
7    8
8    9
dtype: int64

In [ ]:
l2=[1,2,3,4,5,6,7]
d1=pd.Series(l2)
d1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
d1[1:4]

1    2
2    3
3    4
dtype: int64

In [ ]:
d1[-5:]

2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
d1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
dtype: int64

In [ ]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([10,20,30,40,50])
s1+s2

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
s1[3]+s2[4]

54

In [ ]:
s1[0:3]+s2[1:4]

0     NaN
1    22.0
2    33.0
3     NaN
dtype: float64

In [ ]:
s1-3

0   -2
1   -1
2    0
3    1
4    2
5    3
6    4
7    5
8    6
dtype: int64

In [ ]:
s2*4

0     40
1     80
2    120
3    160
4    200
dtype: int64

In [ ]:
s2/3

0     3.333333
1     6.666667
2    10.000000
3    13.333333
4    16.666667
dtype: float64

In [ ]:
s2//3

0     3
1     6
2    10
3    13
4    16
dtype: int64

In [ ]:
x=pd.DataFrame({'name3':['anay','bob','matt'],'marks':[56,78,98]})
x

name3  marks
0  anay     56
1   bob     78
2  matt     98

In [ ]:
s=pd.read_csv('/content/blender_benchmarking_opendata.csv')
s.head()

FileNotFoundError: ignored

In [ ]:
s.tail()

In [ ]:
s.size

In [ ]:
s.shape

In [ ]:
s.describe()

In [ ]:
s.info()

In [ ]:
s.iloc[0:7,0:3]

In [ ]:
s.loc[0:20,('OS','Compute Type')]

In [ ]:
s.drop(['OS'],axis=1)

In [ ]:
s1=s.drop([3,5,7],axis=0)
s1

In [ ]:
s1.head()

In [ ]:
z=pd.read_csv('/content/data.csv')
z


In [ ]:
import pandas as pd
z.mean()

In [ ]:
z.median()

In [ ]:
z.max()

In [ ]:
print(z.min())

In [ ]:
def make_double(s):
    return s*2
z[['radius_mean']].apply(make_double)
  

In [ ]:
z['diagnosis'].value_counts()

In [ ]:
z.sort_values(by='radius_mean')

In [ ]:
z

In [1]:
import numpy as np
import matplotlib.pyplot as plt
x=np.arange(1,11)


In [ ]:
x

In [ ]:
y=3*x

In [ ]:
y

In [ ]:
plt.plot(x,y)
plt.show

In [ ]:
plt.title("line plot")
plt.xlabel("distance")
plt.ylabel("cost")
plt.plot(x,y)
plt.show

In [ ]:
plt.plot(x,y,color="g",linestyle="--",linewidth="10")
plt.show

In [ ]:
y1=y*3
y2=y*5
y1

In [ ]:
y2

In [ ]:
plt.plot(x,y1,color="r",linestyle=":",linewidth="5")
plt.plot(x,y2,color="g",linewidth="3")
plt.title("two line plot")
plt.xlabel("distance")
plt.ylabel("speed")
plt.show



In [ ]:
plt.subplot(2,1,1)
plt.plot(x,y1,color="r",linestyle=":",linewidth="5")
plt.subplot(2,1,2)
plt.plot(x,y2,color="g",linewidth="3")
plt.title("two line plot")
plt.xlabel("distance")
plt.ylabel("speed")
plt.show



In [ ]:
students={"satyam":45,"sachin":40,"yogesh":39,"mayuree":50,"vikash":30,"eshika":37,"sonali":31}
students
name=list(students.keys())
name
marks=list(students.values())
plt.title("assesment test")
plt.xlabel("Name")
plt.ylabel("Marks")
plt.bar(name,marks)
plt.show

In [ ]:
students={"satyam":45,"sachin":40,"yogesh":39,"mayuree":50,"vikash":30,"eshika":37,"sonali":31}
students
name=list(students.keys())
name
marks=list(students.values())
plt.title("assesment test")
plt.xlabel("students Name")
plt.ylabel("distribution of students Marks")
plt.barh(name,marks,color="g")
plt.show

In [ ]:
x=np.array([2,3,6,4,9,18,56])
y=np.array([3,8,9,12,23,24,10])
plt.scatter(x,y)
plt.show

In [ ]:
x=np.array([2,3,6,4,9,18,56])
y=np.array([3,8,9,12,23,24,10])
plt.scatter(x,y,color="g",s=50,marker="d")
plt.show

In [ ]:
a=3*x
a

In [ ]:
b=y*3
b

In [ ]:
plt.scatter(x,a,marker="d",color="r",s=100)
plt.scatter(x,b,marker="h",c="g",s=150)
plt.show

In [ ]:
plt.subplot(2,1,1)
plt.scatter(x,a,marker="d",color="r",s=100)
plt.subplot(2,1,2)
plt.scatter(x,b,marker="h",c="g",s=150)
plt.show

In [ ]:
list1=[1,3,4,5,6,3,2,12,4,5,6,3,3,5,5,5,5]
plt.hist(list1,color="g")
plt.xlabel("number")
plt.ylabel("fequency")
plt.show

In [ ]:
list1=[1,3,4,5,6,3,2,12,4,5,6,3,3,5,5,5,5]
plt.hist(list1,color="y",bins=6)
plt.xlabel("number")
plt.ylabel("fequency")
plt.show

In [ ]:
import pandas as pd

In [ ]:
 iris=pd.read_csv("/content/Iris.csv")

In [ ]:
iris.head()

In [ ]:
plt.hist(iris["SepalLengthCm"],color="y",bins=20)
plt.show

In [ ]:
import matplotlib.pyplot as plt
s=[1,3,5,6,7,89,2,12]
a=[3,5,7,9,5,7,8,12]
t=[4,6,1,6,12,5,9,0]
sat=list([s,a,t])
plt.boxplot(sat)
plt.show


In [ ]:
s=[1,3,5,6,7,89,2,12]
a=[3,5,7,9,5,7,8,12]
t=[4,6,1,6,12,5,9,0]
sat=list([s,a,t])
plt.violinplot(sat,showmedians=True)
plt.show

In [ ]:
Students=["satyam","vikas","yogesh","sachin","mayuree","eshika"]
Marks=[36,32,31,37,42,40]


In [ ]:
plt.pie(Marks,labels=Students)
plt.show

In [ ]:
plt.pie(Marks,labels=Students,autopct="%0.2f%%",colors=["yellow","blue","green","orange","black","red"])

plt.show

In [ ]:
plt.pie(Marks,labels=Students,radius=2,autopct="%0.2f%%")
plt.pie([1],radius=1,colors=["black"])
plt.show

In [ ]:
import seaborn as sns
from matplotlib import pyplot as plt

fmri=sns.load_dataset("fmri")
fmri

In [ ]:
fmri.head()

In [ ]:
fmri.shape

In [ ]:
sns.lineplot(x="timepoint",y="signal",data=fmri)
plt.show

In [ ]:
sns.lineplot(x="timepoint",y="signal",data=fmri,hue="event")
plt.show

In [ ]:
sns.lineplot(x="timepoint",y="signal",data=fmri,hue="event",style="event")
plt.show

In [ ]:
sns.lineplot(x="timepoint",y="signal",data=fmri,hue="event",style="event",markers=True)
plt.show

In [ ]:
#barplot


In [ ]:
import pandas as pd
pokemon=pd.read_csv("/content/archive (1).zip")


In [ ]:
pokemon.size

In [ ]:
pokemon.shape

In [ ]:
pokemon.head()

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon)
plt.show

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon)
sns.set(style="whitegrid")
plt.show

In [ ]:
sns.barplot(x="is_legendary",y="weight_kg",data=pokemon)
sns.set(style="whitegrid")
plt.show

In [ ]:
sns.barplot(x="is_legendary",y="speed",hue="generation",data=pokemon)
plt.show()

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon,palette="rocket")
plt.show()

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon,palette="vlag")
plt.show()

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon,palette="Blues_d")
plt.show()

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon,palette="muted")
plt.show()

In [ ]:
# many palette available

In [ ]:
#Accent’, ‘Accent_r’, ‘Blues’, ‘Blues_r’, ‘BrBG’, ‘BrBG_r’, ‘BuGn’, ‘BuGn_r’, ‘BuPu’, ‘BuPu_r’, ‘CMRmap’, ‘CMRmap_r’, ‘Dark2’, ‘Dark2_r’, ‘GnBu’, ‘GnBu_r’,  ‘Greens’, ‘Greens_r’, ‘Greys’, ‘Greys_r’, ‘OrRd’, ‘OrRd_r’, ‘Oranges’, ‘Oranges_r’,  ‘PRGn’, ‘PRGn_r’, ‘Paired’, ‘Paired_r’, ‘Pastel1’, ‘Pastel1_r’, ‘Pastel2’,  ‘Pastel2_r’, ‘PiYG’, ‘PiYG_r’, ‘PuBu’, ‘PuBuGn’, ‘PuBuGn_r’, ‘PuBu_r’, ‘PuOr’, ‘PuOr_r’, ‘PuRd’, ‘PuRd_r’, ‘Purples’, ‘Purples_r’, ‘RdBu’, ‘RdBu_r’, ‘RdGy’, ‘RdGy_r’, ‘RdPu’, ‘RdPu_r’, ‘RdYlBu’, ‘RdYlBu_r’, ‘RdYlGn’, ‘RdYlGn_r’, ‘Reds’, ‘Reds_r’, ‘Set1’, ‘Set1_r’, ‘Set2’, ‘Set2_r’, ‘Set3’, ‘Set3_r’, ‘Spectral’, ‘Spectral_r’, ‘Wistia’, ‘Wistia_r’, ‘YlGn’, ‘YlGnBu’, ‘YlGnBu_r’, ‘YlGn_r’, ‘YlOrBr’, ‘YlOrBr_r’, ‘YlOrRd’, ‘YlOrRd_r’, ‘afmhot’, ‘afmhot_r’, ‘autumn’, ‘autumn_r’, ‘binary’, ‘binary_r’,  ‘bone’, ‘bone_r’, ‘brg’, ‘brg_r’, ‘bwr’, ‘bwr_r’, ‘cividis’, ‘cividis_r’, ‘cool’, ‘cool_r’,  ‘coolwarm’, ‘coolwarm_r’, ‘copper’, ‘copper_r’, ‘cubehelix’, ‘cubehelix_r’, ‘flag’, ‘flag_r’,  ‘gist_earth’, ‘gist_earth_r’, ‘gist_gray’, ‘gist_gray_r’, ‘gist_heat’, ‘gist_heat_r’, ‘gist_ncar’,  ‘gist_ncar_r’, ‘gist_rainbow’, ‘gist_rainbow_r’, ‘gist_stern’, ‘gist_stern_r’, ‘gist_yarg’,  ‘gist_yarg_r’, ‘gnuplot’, ‘gnuplot2’, ‘gnuplot2_r’, ‘gnuplot_r’, ‘gray’, ‘gray_r’, ‘hot’, ‘hot_r’,  ‘hsv’, ‘hsv_r’, ‘icefire’, ‘icefire_r’, ‘inferno’, ‘inferno_r’, ‘jet’, ‘jet_r’, ‘magma’, ‘magma_r’,  ‘mako’, ‘mako_r’, ‘nipy_spectral’, ‘nipy_spectral_r’, ‘ocean’, ‘ocean_r’, ‘pink’, ‘pink_r’,  ‘plasma’, ‘plasma_r’, ‘prism’, ‘prism_r’, ‘rainbow’, ‘rainbow_r’, ‘rocket’, ‘rocket_r’,  ‘seismic’, ‘seismic_r’, ‘spring’, ‘spring_r’, ‘summer’, ‘summer_r’, ‘tab10’, ‘tab10_r’,’tab20′, ‘tab20_r’, ‘tab20b’, ‘tab20b_r’, ‘tab20c’, ‘tab20c_r’, ‘terrain’, ‘terrain_r’, ‘turbo’,  ‘turbo_r’, ‘twilight’, ‘twilight_r’, ‘twilight_shifted’, ‘twilight_shifted_r’, ‘viridis’,  ‘viridis_r’, ‘vlag’, ‘vlag_r’, ‘winter’, ‘winter_r’

In [ ]:
sns.barplot(x="is_legendary",y="speed",data=pokemon,color="green")
plt.show()

In [ ]:
import pandas as pd
iris=pd.read_csv("/content/Iris.csv")


In [ ]:
iris

In [ ]:
sns.scatterplot(x="SepalLengthCm",y="PetalLengthCm",data=iris)
plt.show

In [ ]:
sns.scatterplot(x="SepalLengthCm",y="PetalLengthCm",data=iris,hue="Species")
plt.show

In [ ]:
sns.scatterplot(x="SepalLengthCm",y="PetalLengthCm",data=iris,hue="PetalLengthCm")
sns.set(style="whitegrid")
plt.show

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd



In [ ]:
diamond=pd.read_csv("/content/archive (7).zip")

In [ ]:
diamond.head()

In [ ]:
sns.distplot(diamond["price"])
plt.show

In [ ]:
sns.distplot(diamond["price"],hist=False)
plt.show

In [ ]:
sns.distplot(diamond["price"],color="g")
plt.show

In [ ]:
sns.distplot(diamond["price"],color="g",kde=False,bins=10)#for remove fequencyline we you kde
plt.show

In [ ]:
sns.distplot(diamond["price"],color="g",vertical=True)
plt.show

In [ ]:
#jointplot


### **jointplot is a combination of scatterplot and histogram**

In [ ]:
iris=pd.read_csv("/content/Iris.csv")


In [ ]:
iris.head()

In [ ]:
sns.jointplot(x="SepalLengthCm",y="PetalLengthCm",data=iris)
plt.show

In [ ]:
sns.jointplot(x="SepalLengthCm",y="PetalLengthCm",data=iris,color="olive")
plt.show

In [ ]:
sns.jointplot(x="SepalLengthCm",y="PetalLengthCm",data=iris,color="olive",kind="reg")
plt.show #using kind we can show regression and other things

In [ ]:
churn=pd.read_csv("/content/churn.csv")
churn.head()

In [ ]:
sns.boxplot(y="tenure",x="Churn",data=churn)
plt.show()

In [ ]:
sns.boxplot(x="InternetService",y="",data=churn)
plt.show

In [ ]:
sns.boxplot(x="Contract",y="tenure",data=churn,palette="OrRd")
plt.show

In [ ]:
sns.boxplot(x="Contract",y="tenure",data=churn,palette="OrRd",linewidth=3)
plt.show

In [ ]:
sns.boxplot(x="Contract",y="tenure",data=churn,order=["Two year","One year","Month-to-month"],palette="OrRd",linewidth=4)
plt.show

In [ ]:
sns.boxplot(x="Contract",y="tenure",data=churn,order=["Two year","One year","Month-to-month"],linewidth=4,hue="PaymentMethod")
plt.show

In [ ]:
iris.head()

In [ ]:
#pair-plot

In [ ]:
df=sns.load_dataset("iris")
sns.pairplot(df,hue="species")